version: '3.8'
services:
  jupyter:
    container_name: jupyter
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 8888:8888
    # init: true
    # stdin_open: true
    # tty: true
    volumes:
      - ../src:/app/src
